name: check

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    -   cron: '0 3 * * *'

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-plugin:
    strategy:
      matrix:
        platform-version: [ 232, 233 ]

    env:
      ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      # Sets `ORG_GRADLE_PROJECT_version` environment variable to override plugin version
      # based on build number and platform version.
      # For example, for build number `1234` and platform version `232` produces `1234-2023.2-SNAPSHOT`
      - name: Calculate version
        run: |
          platform_version="${{ matrix.platform-version }}"
          echo "ORG_GRADLE_PROJECT_version=${{ github.run_number }}-20${platform_version:0:-1}.${platform_version: -1}-SNAPSHOT" >> $GITHUB_ENV

      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ":buildPlugin"

      - name: Upload plugin archive
        uses: actions/upload-artifact@v3
        with:
          name: intellij-micropython-${{ env.ORG_GRADLE_PROJECT_version }}
          path: build/distributions/intellij-micropython-${{ env.ORG_GRADLE_PROJECT_version }}.zip
